ERROR - 2022-12-08 10:53:31 --> Error connecting to the database: mysqli_sql_exception: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\simasjid-ci4\system\Database\MySQLi\Connection.php:171
Stack trace:
#0 C:\xampp\htdocs\simasjid-ci4\system\Database\MySQLi\Connection.php(171): mysqli->real_connect('localhost', 'root', '', 'db-simasjid-ci4', 3306, '', 0)
#1 C:\xampp\htdocs\simasjid-ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 C:\xampp\htdocs\simasjid-ci4\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#3 C:\xampp\htdocs\simasjid-ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 C:\xampp\htdocs\simasjid-ci4\app\Models\ModelAdmin.php(13): CodeIgniter\Database\BaseBuilder->get()
#5 C:\xampp\htdocs\simasjid-ci4\app\Controllers\Home.php(24): App\Models\ModelAdmin->ViewSetting()
#6 C:\xampp\htdocs\simasjid-ci4\system\CodeIgniter.php(904): App\Controllers\Home->index()
#7 C:\xampp\htdocs\simasjid-ci4\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#8 C:\xampp\htdocs\simasjid-ci4\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#9 C:\xampp\htdocs\simasjid-ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#10 C:\xampp\htdocs\simasjid-ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#11 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: No connection could be made because the target machine actively refused it in C:\xampp\htdocs\simasjid-ci4\system\Database\MySQLi\Connection.php:215
Stack trace:
#0 C:\xampp\htdocs\simasjid-ci4\system\Database\BaseConnection.php(382): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 C:\xampp\htdocs\simasjid-ci4\system\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
#2 C:\xampp\htdocs\simasjid-ci4\system\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 C:\xampp\htdocs\simasjid-ci4\app\Models\ModelAdmin.php(13): CodeIgniter\Database\BaseBuilder->get()
#4 C:\xampp\htdocs\simasjid-ci4\app\Controllers\Home.php(24): App\Models\ModelAdmin->ViewSetting()
#5 C:\xampp\htdocs\simasjid-ci4\system\CodeIgniter.php(904): App\Controllers\Home->index()
#6 C:\xampp\htdocs\simasjid-ci4\system\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
#7 C:\xampp\htdocs\simasjid-ci4\system\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#8 C:\xampp\htdocs\simasjid-ci4\public\index.php(67): CodeIgniter\CodeIgniter->run()
#9 C:\xampp\htdocs\simasjid-ci4\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#10 {main}
CRITICAL - 2022-12-08 10:53:31 --> Unable to connect to the database.
Main connection [MySQLi]: No connection could be made because the target machine actively refused it
in SYSTEMPATH\Database\BaseConnection.php on line 418.
 1 SYSTEMPATH\Database\BaseConnection.php(588): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1585): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `tbl_setting`
WHERE `id` = :id:', [...], false)
 3 APPPATH\Models\ModelAdmin.php(13): CodeIgniter\Database\BaseBuilder->get()
 4 APPPATH\Controllers\Home.php(24): App\Models\ModelAdmin->ViewSetting()
 5 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Home->index()
 6 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 7 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 8 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 9 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-08 12:11:31 --> Maximum execution time of 60 seconds exceeded
in APPPATH\Controllers\Admin.php on line 38.
 1 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
CRITICAL - 2022-12-08 12:12:13 --> file_get_contents(): SSL: An existing connection was forcibly closed by the remote host
in APPPATH\Controllers\Home.php on line 27.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(): SSL: An existing connection was forcibly closed by the remote host', 'APPPATH\\Controllers\\Home.php', 27)
 2 APPPATH\Controllers\Home.php(27): file_get_contents('https://api.myquran.com/v1/sholat/jadwal/0710/2022/12/08')
 3 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-08 03:12:07 --> file_get_contents(): php_network_getaddresses: getaddrinfo for api.myquran.com failed: No such host is known. 
in APPPATH\Controllers\Home.php on line 27.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(): php_network_getaddresses: getaddrinfo for api.myquran.com failed: No such host is known. ', 'APPPATH\\Controllers\\Home.php', 27)
 2 APPPATH\Controllers\Home.php(27): file_get_contents('https://api.myquran.com/v1/sholat/jadwal/0710/2022/12/08')
 3 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
CRITICAL - 2022-12-08 03:12:19 --> file_get_contents(): php_network_getaddresses: getaddrinfo for api.myquran.com failed: No such host is known. 
in APPPATH\Controllers\Home.php on line 27.
 1 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'file_get_contents(): php_network_getaddresses: getaddrinfo for api.myquran.com failed: No such host is known. ', 'APPPATH\\Controllers\\Home.php', 27)
 2 APPPATH\Controllers\Home.php(27): file_get_contents('https://api.myquran.com/v1/sholat/jadwal/0710/2022/12/08')
 3 SYSTEMPATH\CodeIgniter.php(904): App\Controllers\Home->index()
 4 SYSTEMPATH\CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Home))
 5 SYSTEMPATH\CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 6 FCPATH\index.php(67): CodeIgniter\CodeIgniter->run()
 7 SYSTEMPATH\Commands\Server\rewrite.php(43): require_once('FCPATH\\index.php')
